# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 CERN.
#
# cds-migrator-kit is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true
  allow_failures:
    # To allow failures, you need to specify the full environment
    - env: REQUIREMENTS=devel

cache:
  - pip

env:
  - REQUIREMENTS=release DEPLOY=true

python:
  - "3.6"

before_install:
  - "nvm install 6; nvm use 6"
  - "travis_retry pip install pip==20.0.2 setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e all --level=pypi setup.py > .travis-release-requirements.txt"

install:
  - "travis_retry pip install pyOpenSSL"
  - "travis_retry pip install -e .[all]"
  - "travis_retry pip install -r requirements-devel.txt"
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: inveniosoftware
  password:
    secure: TODO:PYPISECUREHASH
  distributions: "compile_catalog sdist bdist_wheel"
  on:
    tags: true
    python: "3.6"
    repo: CERNDocumentServer/cds-migrator-kit
    condition: $DEPLOY = true
